apiVersion: apps/v1
kind: Deployment
metadata:
  name: union-app-deployment
  labels:
    app: union-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: union-backend
  template:
    metadata:
      labels:
        app: union-backend
    spec:
      containers:
      - name: union-backend
        image: union-backend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: CONNECTION_URL
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata: 
  name: union-service
spec:
  selector:
    app: union-backend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
